### ISSUE TITLE
Docker build error: pip install pyannote-core[notebook] failure

### ISSUE THREAD

**Issue by tompierce** [pyannote/pyannote-video#15]
I'm following the getting started steps at http://nbviewer.jupyter.org/github/pyannote/pyannote-video/blob/master/doc/getting_started.ipynb
But the docker build command fails:

```
Step 9 : RUN pip install pyannote.core[notebook]
 ---> Running in a3bf47f34b5c
Downloading/unpacking pyannote.core[notebook]
Downloading/unpacking numexpr>=2.4.6 (from pyannote.core[notebook])
  Running setup.py (path:/tmp/pip_build_root/numexpr/setup.py) egg_info for package numexpr

    warning: no previously-included files found matching 'numexpr/__config__.py'
    warning: no previously-included files found matching 'RELEASING.txt'
Downloading/unpacking numpy>=1.10.4 (from pyannote.core[notebook])
  Running setup.py (path:/tmp/pip_build_root/numpy/setup.py) egg_info for package numpy
    Running from numpy source directory.

    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.pyo' found anywhere in distribution
    warning: no previously-included files matching '*.pyd' found anywhere in distribution
Downloading/unpacking six>=1.10.0 (from pyannote.core[notebook])
  Downloading six-1.10.0-py2.py3-none-any.whl
Downloading/unpacking networkx>=1.10.0 (from pyannote.core[notebook])
Downloading/unpacking pandas>=0.17.1 (from pyannote.core[notebook])
  Running setup.py (path:/tmp/pip_build_root/pandas/setup.py) egg_info for package pandas

    package init file 'pandas/io/tests/sas/__init__.py' not found (or not a regular file)
    warning: no files found matching 'README.rst'
    no previously-included directories found matching 'doc/build'
    warning: no directories found matching 'examples'
    warning: no previously-included files matching '*.so' found anywhere in distribution
    warning: no previously-included files matching '*.pyd' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*~' found anywhere in distribution
    warning: no previously-included files matching '#*' found anywhere in distribution
    warning: no previously-included files matching '.git*' found anywhere in distribution
    warning: no previously-included files matching '.DS_Store' found anywhere in distribution
    warning: no previously-included files matching '*.png' found anywhere in distribution
Downloading/unpacking pyannote-banyan>=0.1.6 (from pyannote.core[notebook])
  Running setup.py (path:/tmp/pip_build_root/pyannote-banyan/setup.py) egg_info for package pyannote-banyan

Downloading/unpacking xarray>=0.7.0 (from pyannote.core[notebook])
Downloading/unpacking bottleneck>=1.0.0 (from pyannote.core[notebook])
  Running setup.py (path:/tmp/pip_build_root/bottleneck/setup.py) egg_info for package bottleneck

    warning: no previously-included files found matching 'bottleneck/src/reduce.c'
    warning: no previously-included files found matching 'bottleneck/src/move.c'
    warning: no previously-included files found matching 'bottleneck/src/nonreduce.c'
    warning: no previously-included files found matching 'bottleneck/src/nonreduce_axis.c'
    warning: no previously-included files matching '*' found under directory 'doc/build'
Downloading/unpacking simplejson>=3.8.1 (from pyannote.core[notebook])
  Running setup.py (path:/tmp/pip_build_root/simplejson/setup.py) egg_info for package simplejson

Requirement already satisfied (use --upgrade to upgrade): jupyter>=1.0.0; extra == "notebook" in /usr/local/lib/python2.7/dist-packages (from pyannote.core[notebook])
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1090, in prepare_files
    req_to_install.check_if_exists()
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 810, in check_if_exists
    self.satisfied_by = pkg_resources.get_distribution(self.req)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 557, in get_distribution
    dist = get_provider(dist)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 431, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
IndexError: list index out of range

Storing debug log for failure in /root/.pip/pip.log
The command '/bin/sh -c pip install pyannote.core[notebook]' returned a non-zero code: 2
```

Any ideas?

**Comment by hbredin** [comment]
Should be fixed in latest release (1.3.14).

**Comment by xjq95** [comment]
@hbredin  still not work?   

`Running setup.py install for pyannote-banyan: started
    Running setup.py install for pyannote-banyan: still running...
    Running setup.py install for pyannote-banyan: finished with status 'error'
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;**file**='/tmp/pip-build-VRLs2i/pyannote-banyan/setup.py';f=getattr(tokenize, 'open', open)(**file**);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, **file**, 'exec'))" install --record /tmp/pip-r0jFF8-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/banyan
    copying banyan/**init**.py -> build/lib.linux-x86_64-2.7/banyan
    copying banyan/_common_base.py -> build/lib.linux-x86_64-2.7/banyan
    copying banyan/_dict.py -> build/lib.linux-x86_64-2.7/banyan
    copying banyan/_dummy_key.py -> build/lib.linux-x86_64-2.7/banyan
    copying banyan/_frozen_dict.py -> build/lib.linux-x86_64-2.7/banyan
    copying banyan/_frozen_set.py -> build/lib.linux-x86_64-2.7/banyan
    copying banyan/_min_gap_updator.py -> build/lib.linux-x86_64-2.7/banyan
    copying banyan/_node.py -> build/lib.linux-x86_64-2.7/banyan
    copying banyan/_overlapping_intervals_updator.py -> build/lib.linux-x86_64-2.7/banyan
    copying banyan/_rank_updator.py -> build/lib.linux-x86_64-2.7/banyan
    copying banyan/_set.py -> build/lib.linux-x86_64-2.7/banyan
    copying banyan/_trace.py -> build/lib.linux-x86_64-2.7/banyan
    copying banyan/_views.py -> build/lib.linux-x86_64-2.7/banyan
    running build_ext
    building 'banyan_c' extension
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/banyan
    creating build/temp.linux-x86_64-2.7/banyan/_int_imp
    creating build/temp.linux-x86_64-2.7/banyan/_int_int
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/local/include -Ibanyan -I/usr/include/python2.7 -c banyan/dict_tree.cpp -o build/temp.linux-x86_64-2.7/banyan/dict_tree.o
    cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++ [enabled by default]
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/local/include -Ibanyan -I/usr/include/python2.7 -c banyan/frozen_dict_tree.cpp -o build/temp.linux-x86_64-2.7/banyan/frozen_dict_tree.o
    cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++ [enabled by default]
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/local/include -Ibanyan -I/usr/include/python2.7 -c banyan/frozen_set_tree.cpp -o build/temp.linux-x86_64-2.7/banyan/frozen_set_tree.o
    cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++ [enabled by default]
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/local/include -Ibanyan -I/usr/include/python2.7 -c banyan/min_gap_metadata.cpp -o build/temp.linux-x86_64-2.7/banyan/min_gap_metadata.o
    cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++ [enabled by default]
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/local/include -Ibanyan -I/usr/include/python2.7 -c banyan/module.cpp -o build/temp.linux-x86_64-2.7/banyan/module.o
    cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++ [enabled by default]
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/local/include -Ibanyan -I/usr/include/python2.7 -c banyan/node.cpp -o build/temp.linux-x86_64-2.7/banyan/node.o
    cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++ [enabled by default]
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/local/include -Ibanyan -I/usr/include/python2.7 -c banyan/overlapping_intervals_metadata.cpp -o build/temp.linux-x86_64-2.7/banyan/overlapping_intervals_metadata.o
    cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++ [enabled by default]
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/local/include -Ibanyan -I/usr/include/python2.7 -c banyan/rank_metadata.cpp -o build/temp.linux-x86_64-2.7/banyan/rank_metadata.o
    cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++ [enabled by default]
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/local/include -Ibanyan -I/usr/include/python2.7 -c banyan/set_tree.cpp -o build/temp.linux-x86_64-2.7/banyan/set_tree.o
    cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++ [enabled by default]
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/local/include -Ibanyan -I/usr/include/python2.7 -c banyan/tree.cpp -o build/temp.linux-x86_64-2.7/banyan/tree.o
    cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++ [enabled by default]
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/local/include -Ibanyan -I/usr/include/python2.7 -c banyan/tree_view.cpp -o build/temp.linux-x86_64-2.7/banyan/tree_view.o
    cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++ [enabled by default]
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/local/include -Ibanyan -I/usr/include/python2.7 -c banyan/_int_imp/_build_tree_imp.cpp -o build/temp.linux-x86_64-2.7/banyan/_int_imp/_build_tree_imp.o
    cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++ [enabled by default]
    x86_64-linux-gnu-gcc: internal compiler error: Killed (program cc1plus)
    Please submit a full bug report,
    with preprocessed source if appropriate.
    See file:///usr/share/doc/gcc-4.8/README.Bugs for instructions.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 4

```
----------------------------------------
```

Command "/usr/bin/python -u -c "import setuptools, tokenize;**file**='/tmp/pip-build-VRLs2i/pyannote-banyan/setup.py';f=getattr(tokenize, 'open', open)(**file**);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, **file**, 'exec'))" install --record /tmp/pip-r0jFF8-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-VRLs2i/pyannote-banyan/
The command '/bin/sh -c pip install pyannote.core[notebook]' returned a non-zero code: 1
`

**Comment by hbredin** [comment]
@yibanguaiqi I cannot reproduce this error. Did you follow the "getting started" notebook?

**Comment by hbredin** [comment]
Closing because this issue hasn't been active in a while.
